server:
  port: 8060
  servlet:
    context-path: /
    #session:
      #timeout: 600  #session失效时间 单位：秒

spring:
  application:
    name: spring-security-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.243.176:3306/oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root123
    type: com.alibaba.druid.pool.DruidDataSource #指定数据库连接池
    druid:
      initial-size: 5 #初始化连接池大小
      max-active: 20 #最大连接数
      min-idle: 5 #最小空闲连接数
      max-wait: 10000 #最大阻塞等待时间
      remove-abandoned-timeout: 20 #最大连接时间
      remove-abandoned: true #释放时间超过remove-abandoned-timeout的连接
  freemarker:
    template-loader-path: classpath:/templates/ #模版所在位置
    suffix: .ftl #模版后缀
    cache: false #缓存
    charset: UTF-8 #编码格式
    settings:
      number_format: 0 #数字格式化，无小数点
  redis:
    host: 47.98.243.176
    port: 6379
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

oauth2:
  client:
    client-id: guaneoms
    client-secret: secret
    oauth-authorize-url: http://i.guanph.gov.cn/oauth/authorize
    oauth-callback-url: http://eoms.guanph.gov.cn/oauth/callback
    access-token-url: http://i.guanph.gov.cn/oauth/token
  resource:
    oauth-resource-url: http://resource.guanph.gov.cn/user/me


